appid: img2x16
author:
    name: "morphinejh"
category: "Graphics"
description: "mg2x16 is a command line program to convert image files to VERA binary
    streams for the Commander X16.  img2x16 is designed to take a given image, and
    adapt it to a given color palette. It currently only supports 8bpp color depth
    (i.e 16-bit palette entries)."
name: "img2x16"
url:
    source: "https://github.com/morphinejh/img2x16"
version: "Version 0.3"
