appid: bmxfileviewer
author:
    name: "catmeow72"
category: "Graphics"
description: "This program views images made with the BMX format for the Commander
    X16."
name: "BMX File Viewer"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6978&sid=87adc7904c41009a74ad4b9add499957"
version: ""
