appid: x16emulator
author:
    name: "various"
category: "Programming"
description: "This is an emulator for the Commander X16 computer system. It only depends
    on SDL2 and should compile on all modern operating systems."
name: "X16 Emulator"
url:
    source: "https://github.com/x16community/x16-emulator"
version: "48"
