appid: xinfo
author:
    name: "Xiphod"
category: "Editors"
description: "XINFO is a text file viewer with three other special features: Interpret
    control codes for color, support links within the document or to others, word-wrap
    the text."
name: "XINFO"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6924&sid=5a303c5195eb93a4d305dc21389930e2"
version: "v1.8"
