appid: medemo
author:
    name: "Irmen de Jong"
category: "Sound"
description: "This is a adpcm-music streaming demo that I made that also syncs lyrics
    on the screen to the song being played."
name: "medemo"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6498"
    source: "https://cx16forum.com/forum/viewtopic.php?t=6498"
version: ""
