appid: concertomultitrac
author:
    name: "kliepatsch"
category: "Sound"
description: "Concerto Multitrack is a program for making music on the Commander X16.
    It aims to unlock the full potential of 16 PSG oscillators plus 8 FM voices."
name: "Concerto Multitrack"
url:
    source: "https://github.com/biermanncarl/cx16-concerto"
    x16forum: "https://github.com/biermanncarl/cx16-concerto"
version: "v0.8.0-beta.2"
