appid: baccarat
author:
    name: "tallLeRoy"
category: "Games"
description: "Baccarat is a game with some development history. It began as a BASIC
    game in the book 'More BASIC Computer Games' Edited by David H. Ahl and published
    by Workman Publishing New York in 1979."
name: "Baccarat"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7254&sid=aad3aceedfb6154d1584fc24ec2936d8"
version: ""
