appid: puzz
author:
    name: "ceptimus"
category: "Games"
description: "A sliding block puzzle game."
name: "PUZZ"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7689&sid=aad3aceedfb6154d1584fc24ec2936d8"
version: ""
