appid: hazardletusout
author:
    name: "Ultimategilby"
category: "Games"
description: "A new survival platformer game for the NES or favorite emulator. And
    now for the X16!!!"
name: "Hazard Let Us Out!!!"
url:
    website: "https://ultimate-gilby.itch.io/hazard-let-us-out"
version: ""
