appid: minidoku
author:
    name: "ModernRetroDev"
category: "Games"
description: "This is a small and simple Sudoku-like game which should only take one
    to two minutes per round."
name: "Minidoku"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=8917&sid=ae40c1febbade03020241222eb9aa3d3"
version: "1.01"
