appid: damontherocketjoc
author:
    name: "natebarney"
category: "Games"
description: "Damon: The Rocket Jockey is a clone of Nomad: The Space Pirate a C64
    game"
name: "Damon The Rocket Jockey"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7656&sid=ae40c1febbade03020241222eb9aa3d3"
    source: "https://cx16forum.com/forum/viewtopic.php?t=7656&sid=ae40c1febbade03020241222eb9aa3d3"
version: ""
