appid: streamingwavplaye
author:
    name: "Irmen de Jong"
category: "Sound"
description: "This program can play normal .wav sampled music files. Not only that,
    but it streams them from disk rather than loading it all in memory, so that there
    is virtually no limit on how long you want the music to play!"
name: "Streaming .WAV player"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6390"
    source: "https://cx16forum.com/forum/viewtopic.php?t=6390"
version: ""
