appid: vaultofthevindica
author:
    name: "Toboter"
category: "Games"
description: "Explore an everchanging dungeon, battle enemies, find loot and discover
    the secrets of the Vindicator in this unique 3D Roguelike Dungeon Crawl Adventure!"
name: "Vault of the Vindicator"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6918&sid=ae40c1febbade03020241222eb9aa3d3"
version: "1.0"
