appid: crazylander
author:
    name: "DusanStrakl"
category: "Games"
description: "Updated version of Crazy Lander, Moon Lander type game."
name: "Crazy Lander"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6614&sid=aad3aceedfb6154d1584fc24ec2936d8"
version: ""
