appid: x16edit
author:
    name: "Stefan Jakobsson"
category: "Editors"
description: "X16 Edit is a simple text editor for the Commander X16 platform inspired
    by GNU Nano."
name: "X16Edit"
url:
    source: "https://github.com/stefan-b-jakobsson/x16-edit"
    x16forum: "https://github.com/stefan-b-jakobsson/x16-edit"
version: "0.8.3"
