appid: imageviewer
author:
    name: "Irmen de Jong"
category: "Graphics"
description: "Multi file format image viewer for Commander X16. Supports, C64 Koala
    (.koa) and Doodle (.dd/.ddl), IFF ILBM and PBM, including CRNG and CCRT color
    cycling! BMP, PCX, BMX (Commander X16 bitmap file)"
name: "Image Viewer"
url:
    source: "https://github.com/irmen/cx16imageviewer"
    x16forum: "https://github.com/irmen/cx16imageviewer"
version: ""
