appid: tombofanneis
author:
    name: "WauloK"
category: "Games"
description: "An action puzzle game for the Commander X16."
name: "Tomb of Anneis"
url:
    website: "https://suite16.au/"
    x16forum: "https://suite16.au/"
version: ""
