appid: basterm
author:
    name: "Xiphod"
category: "Internet"
description: "Serial terminal for the X16 written in BASIC."
name: "BASTERM"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=8237&sid=5a303c5195eb93a4d305dc21389930e2"
version: "v3"
