appid: textadventurecoll
author:
    name: "fredrik"
category: "Games"
description: "Five collections of great Z-code text adventures for the Commander X16."
name: "Text Adventure Collection"
url:
    website: "https://microheaven.com/ztac/"
    x16forum: "https://microheaven.com/ztac/"
version: ""
