appid: zsmkit
author:
    name: "mooinglemur"
category: "Programming"
description: "ZSMKit is a ZSM playback library for the Commander X16. It aims to be
    an alternative to ZSound, but with several new features and advantages."
name: "ZSMKit"
url:
    source: "https://github.com/mooinglemur/zsmkit"
version: "2.6"
