appid: ghostcrusher
author:
    name: "Jimmy Dansbo"
category: "Games"
description: "In this game you need to crush ghosts between walls before the ghosts
    catch (touch) you. Red walls can not be moved, but green walls can be pushed around."
name: "Ghost Crusher"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6286&sid=7059976c0997eb24da0bcc2921e2ddfa"
version: ""
