appid: tilemaped
author:
    name: "Dacobi"
category: "Graphics"
description: "TilemapEd is a simple tilemap editor specifically for the X16. It's
    not meant to be a recreation of Tiled, but a more simple approach."
name: "TilemapEd"
url:
    source: "https://github.com/dacobi/tilemaped"
version: "1.8.166"
