appid: gamebookcollectio
author:
    name: "fredrik"
category: "Games"
description: "SD Separa has converted nine classic gamebooks (AKA Choose Your Own
    Adventure books) to Z-code format."
name: "Gamebook Collection"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7421&sid=ae40c1febbade03020241222eb9aa3d3"
version: ""
