appid: payroll
author:
    name: "Poe"
category: "Tools"
description: "A VisiCalc Clone. This is a rough draft version of a VisiCalc clone
    for the Commander X16 written in BASIC. It only has the SUM function working right
    now. But hopefully a future version will be more fleshed out."
name: "PAYROLL"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7072&sid=5a303c5195eb93a4d305dc21389930e2"
version: ""
