appid: arthursdayout
author:
    name: "WauloK"
category: "Games"
description: "A text adventure game."
name: "Arthur's Day Out"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=8261&sid=ae40c1febbade03020241222eb9aa3d3"
version: ""
