appid: memorymatch
author:
    name: "Xiphod"
category: "Games"
description: "A 4x4 memory matching game! Simple rules. Use keyboard or gamepad. Can
    take turns using any gamepad 1-4, end game will show number of guesses and elapsed
    seconds for the round."
name: "Memory Match"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7793&sid=aad3aceedfb6154d1584fc24ec2936d8"
version: ""
