appid: huntthewumpus
author:
    name: "tallLeRoy"
category: "Games"
description: "According to Wikipedia this program was written by Gregory Yob in 1973.
    It was published in Creative Computing as a BASIC game."
name: "Hunt the Wumpus"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=7575&sid=aad3aceedfb6154d1584fc24ec2936d8"
version: ""
