appid: x16emuforlinuxi68
author:
    name: "mobluse"
category: "Tools"
description: "The official X16 emulator build for 32bit Linux i686"
name: "x16emu for Linux i686 (32 bit)"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6433&sid=861eed69f3583ffbad5003776001cac0"
version: "R43"
