appid: x16cell
author:
    name: "TediusTimmy"
category: "Tools"
description: "A spreadsheet program for X16."
name: "X16Cell"
url:
    x16forum: "https://cx16forum.com/forum/viewtopic.php?t=6528&sid=5a303c5195eb93a4d305dc21389930e2"
version: "1.2"
